export const actionTypes = {
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
  UPDATE: 'UPDATE',
  BOOKS_LIST_REQUEST: 'BOOKS_LOAD_REQUEST',
  BOOKS_LIST_SUCCESS: 'BOOKS_LOAD_SUCCESS',
  BOOKS_LIST_FAILURE: 'BOOKS_LOAD_FAILURE', 
  BOOK_PAGE_REQUEST: 'BOOK_PAGE_REQUES',
  BOOK_PAGE_SUCCESS: 'BOOK_PAGE_SUCCESS',
  BOOK_PAGE_FAILURE: 'BOOK_PAGE_FAILURE'
};