export const actionTypes = {
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
  UPDATE: 'UPDATE',
  BOOKS_LIST_REQUEST: 'BOOKS_LOAD_REQUEST', // probably useless
  BOOKS_LIST_SUCCESS: 'BOOKS_LOAD_SUCCESS',
  BOOKS_LIST_FAILURE: 'BOOKS_LOAD_FAILURE', // probably useless
  BOOK_DETAILS_SUCCESS: 'BOOK_PAGE_SUCCESS',
  REQUEST_SUCCESS: 'REQUEST_SUCCESS',
  REQUEST_FAILURE: 'REQUEST_FAILURE',
  GENER_LIST_LOADED: 'GENER_LIST_LOADED',
  AUTHOR_LIST_LOADED: 'AUTHOR_LIST_LOADED',
  PRICE_RANGE_LOADED: 'PRICE_RANGE_LOADED',
  CHANGE_USER_IMG: 'CHANGE_USER_IMG',
  SET_PRICE: 'SET_PRICE',
  SET_RATING: 'SET_RATING',
  SET_AUTHORS: 'SET_AUTHORS',
  FAVORITES_LOADED: 'FAVORITES_LOADED',
  REVIEWS_LOADED: 'REVIEWS_LOADED',
  BOOK_IMAGES_LOADED: 'BOOK_IMAGES_LOADED'
};